# Generated by Django 5.0.6 on 2024-06-19 19:00

import usuario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=usuario.models.User.criaNome),
        ),
    ]
