# Generated by Django 5.0.6 on 2024-06-19 23:57

import usuario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_usuario_id_telefone_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cover',
            field=models.ImageField(upload_to=usuario.models.Usuario.criaNome),
        ),
    ]
