# Generated by Django 5.0.6 on 2024-06-10 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('value', models.FloatField()),
                ('pix_key', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=255)),
                ('award', models.CharField(max_length=255)),
                ('date_start', models.DateTimeField()),
                ('date_finish', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateTimeField()),
                ('rifa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rifa.rifa')),
            ],
        ),
    ]
