# Generated by Django 5.0.6 on 2024-06-13 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0002_alter_number_date_alter_rifa_id_alter_rifa_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='rifa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rifa.rifa'),
        ),
    ]
