# Generated by Django 5.0.6 on 2024-06-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0003_alter_number_rifa_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='rifa',
            name='pix_key',
        ),
        migrations.AddField(
            model_name='rifa',
            name='cover',
            field=models.FileField(null=True, upload_to='rifa/static/rifa/img'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='date_start',
            field=models.DateTimeField(default=None),
        ),
        migrations.CreateModel(
            name='User_common',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Endereco_usuario', to='rifa.endereco')),
            ],
        ),
    ]
