# Generated by Django 5.0.6 on 2024-06-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0005_alter_rifa_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifa',
            name='date_start',
            field=models.DateTimeField(null=True),
        ),
    ]
