# Generated by Django 5.0.6 on 2024-06-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0007_alter_rifa_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifa',
            name='cover',
            field=models.ImageField(upload_to='rifa/static/rifa/img'),
        ),
    ]
