# Generated by Django 5.0.6 on 2024-06-18 16:41

import rifa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0008_alter_rifa_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifa',
            name='cover',
            field=models.ImageField(height_field='250', upload_to=rifa.models.Rifa.criaNome, width_field='250'),
        ),
    ]
